baseURL = "https://utb.vilhelmprytz.se/"
languageCode = "sv"
title = "Vilhelm Prytz - Utbildningsmaterial"

theme = "book"

[params]
    BookSearch = false

    BookRepo = 'https://github.com/VilhelmPrytz/utbildningsmaterial'
    BookEditPath = 'edit/master/content'